# Generated by Django 4.2.2 on 2023-09-28 19:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0011_alter_task_creator"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"permissions": [("custom_task", "Custom Task Permission")]},
        ),
    ]
