# Generated by Django 4.2.2 on 2023-10-18 21:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0013_alter_task_creator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("UNASSIGNED", "Unassigned"),
                    ("IN_PROGRESS", "In Progress"),
                    ("DONE", "Done"),
                    ("ARCHIVED", "Archived"),
                ],
                default="UNASSIGNED",
                max_length=20,
            ),
        ),
    ]
