apiVersion: ENC[AES256_GCM,data:Q58=,iv:y+BBk4Cxg9M2rc/MU5mX9+gmZcR7lRoCmNeg4H+7hhA=,tag:NYp+/uzvoEk2N6WreQZ3dg==,type:str]
kind: ENC[AES256_GCM,data:2nHFLtx4,iv:dvakfsbycyo3qjnVBNfD/55T/q1oYvrBjgSnmHOTltY=,tag:c+HUejHFFHy+Wl6o0yYPAA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:t4bnVEKRt7+nkPXs7XPYisr6Wg==,iv:Eg+jiEwlMGbbyqlaixVmtlB0RZOL39nT7p0gDf8SPzY=,tag:w4Im3UBzfr7ZWd5COFfwQw==,type:str]
type: ENC[AES256_GCM,data:qRvFPXCt,iv:WW15P0PLiBoG9Aikp2LFfFsAxA4APTnzrqtcGGZQoX4=,tag:84SeO/6Sl8evnvEg/IPwVA==,type:str]
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:bHdXJ4k06srRCsktRW3i,iv:YdwYKyjG1j02w5Oov80wjmrG2vsQfBBHsZYBVHW8VeA=,tag:Ta+mMkSHaGU7pTIn/ytqVA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:sG+PpV7y0obHlVb4u1UtzQ==,iv:mpksVb/rbbhJvz/76Gcl4TNnMrhbgLOl8hlJakJWbXI=,tag:5BHwTpo9Sbni1W0BjxrZRw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-11-15T19:45:45Z"
    mac: ENC[AES256_GCM,data:weUIFo/M+tAuXyExDqawhXk7Il7/vr3QJgQcPi8TguX2kNlW0srgBnIzFVj9ZXE4Pt8QGorqlsTWkeZsLBlg6FRAjTIIJcEBtNSu9EvMKm0tKd+vSvTJP0lkzNzt/ajiFGN5/jSm9NYYU0V5GY8Nozz4O+piqIWfJ7qmCyGWNBg=,iv:Q2YqMaDFKhmGI0IxLYiRcknNotj+kqsrivXJ6PHXmhw=,tag:W018SwB4rloacWWHBnm1IA==,type:str]
    pgp:
        - created_at: "2023-11-15T19:18:27Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMAwYvS11e1iTGAQv8CPccs1Ia1a99bAjB/ZUCU6ejVegnTeIxEcPvGfCP7q3F
            NziYkVjY12J+q3eYX6vvsLNBcCq5KJx9jwCNmShTXYi9XWe05REwwrDypGo8Y3oZ
            clfhFJvObniP+Rc6z7MMAgf9tPVXdXHNILF/ktFA8EAG7D9OT+nJXrXVykXZxryi
            KJ9MLd6krwrCSZXzaytnyV/xBBqHm1aYljRFgP7dYXpOWqDvxVKzK6+gtMZvudiy
            cbU1yBtTdAJj7R/1R3zCwFTteEvRlG2KpoqyT9IFM8YSfYloBfd3V8r31hTVy3Um
            nAagEgH+Ne58ejHKVlulFOjHReLoS4MonYUZ3k+pSGegBT4la50MdImBTyowoVx6
            NZZiS14fYKBQxiRR68WX2Zi7fxZG2cWzWaFF8iq9W56ipt7MfgbEYsMC24tmw+AM
            d4YfJA7gMDp6Chs645Eas9r9H7/SyV2DzbAqUe/HXHvTRgwHh2dxZDpzx2tEDjlz
            eKJ/QJjfYinLdt6RugDP1GgBCQIQL0SifZ4jHoWMiy1yZe4lBVBlTTzgT1UhhdD5
            nNv0H9cN3wvTKkP72LhX+adEJ//aSvn1c3OtBDboE435OKe8fxRAS8PQlAi4d9Re
            KnjVHxz29hZDidq5oUhMxGFlOvK1xQnfOQ==
            =8qz7
            -----END PGP MESSAGE-----
          fp: 0BDAFCB6671CA54E1DB190428847B964B421D302
    unencrypted_suffix: _unencrypted
    version: 3.7.3
