# Generated by Django 4.2.2 on 2023-09-03 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0006_task_status_check"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="version",
            field=models.IntegerField(default=0),
        ),
    ]
